### ISSUE TITLE
Add license file.

### ISSUE THREAD

**Issue by jhlegarreta** [richardbeare/parabolicMorphology#6]
The license file is missing from this module.

**Comment by richardbeare** [comment]
Noted - will select a standard one ASAP.

**Comment by jhlegarreta** [comment]
Thanks @richardbeare ! I think the ITK remote module template/SW guide dictate the policies for accepted license types.

**Comment by richardbeare** [comment]
Apache 2.0 license file added.

**Comment by jhlegarreta** [comment]
Thanks @richardbeare !

Closing thanks to addition in commit f7d058f.
